spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: Password1!
    url: 'jdbc:postgresql://localhost:5432/testdb'
    username: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: vamsi
      password: pwd
  application:
    name: SECURITY_SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

