spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: Password1!
    url: 'jdbc:postgresql://localhost:5432/test'
    username: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect